version: '3.5'
services:
  api:
    container_name: api
    image: jkm00/spring-boot
    ports:
      - 80:8080
    environment:
      - 'SPRING_PROFILE_ACTIVE=prod'
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Make sure database is up and running before starting the api
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: database
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
